knoxville-utilities-board/ember-nrg-ui

- addon/components/nrg-form-container/component.js
> fix(form-container): remove unused code

- addon/components/nrg-list/component.js
> feat(nrg-list): add ability to customize search param

- addon/components/nrg-sidebar-menu-item/component.js
- addon/components/nrg-sidebar-menu-item/template.hbs
- addon/components/nrg-sidebar-menu/template.hbs
- addon/styles/_application.scss
> fix(sidebar-menu): group headers now align correctly with other items

- addon/components/nrg-appbar/component.js
- addon/components/nrg-sidebar/component.js
- addon/responsive/service.js
> fix(responsive): Add computed breakpoint groups

- addon/styles/_list.scss
- tests/dummy/app/view-components/nrg-list/controller.js
> fix: Add ellipsis overflow to list filter dropdown

- addon/components/nrg-appbar/template.hbs
- addon/styles/_application.scss
> fix: Add ellipsis overflow to app title

- addon/components/nrg-modal/component.js
- addon/components/nrg-modal/template.hbs
This wil correct some layout issues when multiple modals are opened.
> fix(modal): refresh visible modals on modal closure

- addon/components/nrg-sidebar/component.js
> fix(sidebar): resize event function changed with a past refactor

- addon/components/nrg-lightbox-container/component.js
- addon/components/nrg-lightbox-container/template.hbs
- addon/components/nrg-lightbox-thumbnail/component.js
- addon/components/nrg-lightbox-thumbnail/template.hbs
- addon/lightbox/service.js
- package.json
- tests/acceptance/sidebar-test.js
- tests/dummy/app/view-components/nrg-lightbox/controller.js
- tests/dummy/app/view-components/nrg-lightbox/template.hbs
- tests/unit/lightbox/service-test.js
- Lightbox detail can now update dynamically
- Lightbox infrastructure now uses closure actions
- Removing and adding new thumbnails are more reliable
> refactor(lightbox): better detail support and closure actions

- addon/application/settings.js
- addon/components/nrg-appbar/template.hbs
* fix: Prevent "DEV" from displaying before title loads
* fix: Show loading indicator while title is loading
> fix(nrg-appbar): Render app title appropriately

- addon/components/nrg-list/component.js
> fix(nrg-list): Extract refresh action to action handler

- addon/components/nrg-search/component.js
- package.json
- tests/dummy/app/view-components/nrg-search/controller.js
I'm having issues triggering the keydown events properly for the tests, so I'll create a separate PR for those. `nrg-dropdown` also likely needs some tests for using the arrow keys
> fix(nrg-search): Options can be selected

- addon/styles/_application.scss
- package.json
Home cards were not getting hidden properly
> fix: raise the specificity of .is-visually-hidden

- addon/components/nrg-context-menu/component.js
- addon/components/nrg-context-menu/template.hbs
- addon/context-menu/service.js
[Jira Card](https://kubprojects.atlassian.net/browse/KUBAPPS-827?atlOrigin=eyJpIjoiODFkMzZiMDVhNDNhNGUzOGE2YTUxMTc4MzMxZGI4ZDYiLCJwIjoiaiJ9)
[Related PR](http://github.kub.org/web/ember-kubapps-ui/pull/446)
> chore: Add disabled property for context-menu

- addon/components/nrg-modal-container/modal-wrapper/component.js
- addon/components/nrg-modal/component.js
- package.json
> feat: Added ability to toggle scrolling of modal content

- addon/components/nrg-lightbox-container/component.js
- addon/components/nrg-lightbox-container/template.hbs
- addon/styles/_lightbox.scss
- tests/dummy/app/view-components/nrg-lightbox/route.js
Works on devices all the way down to iPhone 5.
> fix: Contain large images and prevent control panel from moving based on size of image

- addon/components/nrg-dropdown/item/component.js
- addon/components/nrg-dropdown/menu/template.hbs
- addon/components/nrg-dropdown/template.hbs
- addon/context-menu/service.js
- tests/dummy/app/application/route.js
> fix(dropdown): do not highlight entire dropdown on hover

- addon/components/nrg-modal-container.hbs
- addon/components/nrg-modal-container.js
- addon/templates/components/nrg-modal-container.hbs
https://kubprojects.atlassian.net/browse/FWS-1375
> feat: convert nrg-modal-container to glimmer

- addon/components/nrg-modal-container/modal-wrapper.hbs
- addon/components/nrg-modal-container/modal-wrapper.js
- addon/components/nrg-modal.hbs
- addon/components/nrg-modal.js
- addon/services/modal.js
- addon/templates/components/nrg-modal.hbs
- tests/dummy/app/view-components/nrg-modal/controller.js
- tests/dummy/app/view-components/nrg-modal/template.hbs
https://kubprojects.atlassian.net/browse/FWS-1376
> feat: convert nrg-modal to glimmer component

- tests/dummy/app/index.html
> fix: Odd css issue caused by prettier

- blueprints/ember-nrg-ui/files/__config__/content-security-policy.js
- package.json
Allow for easier kubapps-ui integration
> feat: Update csp file to follow documentation

- addon/components/nrg-home-cards/home-card.js
- package.json
Avoid creating new window without destination
> fix: Improve home card linking

- addon/components/nrg-datetime/calendar.js
- package.json
> fix: Datetime calendar render on null value

- addon/components/nrg-datetime/calendar.hbs
- tests/dummy/app/components/freestyle/forms/datetime.js
- tests/integration/components/nrg-datetime/calendar-test.js
[KUBAPPS-1692](https://kubprojects.atlassian.net/browse/KUBAPPS-1692)
> fix: Update calendar time

- addon/components/nrg-dropdown/component.js
- package.json
This calculates where the user clicks, if it's in the scrollbar region, don't close the dropdown.
> fix: Allow user to click on scrollbar

- addon/services/whats-new.js
- package.json
This has been tested and confirmed working, so there shouldn't be any other changes necessary.
> fix(whats-new): Track isOpen correctly

- addon/components/nrg-search.hbs
- addon/components/nrg-search.js
- addon/styles/_search.scss
- addon/styles/addon.scss
- package.json
- tests/dummy/app/components/freestyle/search.hbs
- tests/integration/components/nrg-search-test.js
This is the same as #566 but backported to`4.1.x`.
> feat: New clear option on search ( backport )

- addon/services/application.js
- package.json
https://kubprojects.atlassian.net/browse/KUBAPPS-2192
> fix: Remove repo from page title

- addon/components/nrg-side-by-side/placeholder.hbs
- package.json
- tests/dummy/app/components/freestyle/side-by-side.hbs
- tests/integration/components/nrg-side-by-side/placeholder-test.js
> feat(side-by-side): Add icon to placeholder
