addon/components/nrg-context-menu/component.js

This was causing layout issues within the appbar.
fixes #63

fix(context-menu): remove unneccessary wrapping div

---

addon/components/nrg-dropdown/component.js

`showError` recomputing could cause the dropdown to not close correctly, and the UI element would "break" the form.
It appears to be on the lines of a race condition because not all validators have the issue.

fix(dropdown): "validation" caused dropdown to not close correctly

---

ember-cli-build.js
package.json
yarn.lock

- A bug in semantic prevented mobile scrolling when hidden modal is present
- This pins semantic UI CSS version until bug is corrected
- Outline and brand fonts were not copied over to dist folder
- Semantic ember addon hasn't been released in a while so retrieving from Github

fix: pin semantic ember addon and semantic css to specific versions

---

addon/components/nrg-modal/component.js
addon/components/nrg-modal/template.hbs
tests/dummy/app/view-components/nrg-modal/template.hbs

This PR is in response to this issue from Semantic UI. https://github.com/Semantic-Org/Semantic-UI/issues/4860#issuecomment-297702810
It was discovered that the popup for the datetime component was getting destroyed when inside of a modal.

fix(modal): add option to render modal body only after opened

---

addon/components/nrg-application/component.js
addon/instance-initializers/breakpoints-override.js
app/initializers/breakpoints-override.js
app/instance-initializers/breakpoints-override.js
tests/unit/instance-initializers/breakpoints-override-test.js

This was caused by a change after new release to prevent apps from having to declare a `breakpoints.js` in the app. Due to timing, this needs to be a instance-initializer instead of an initializer.

fix: toggling sidebar didn't work on big screens

---

addon/components/nrg-dropdown/item/template.hbs

Attempting to pass extra attributes, notably `data-test-*` attributes to an item in the dropdown would skip the attributes in rendering.

fix(dropdown/item): Pass extra attributes to div

---

addon/components/nrg-dropdown/component.js
addon/components/nrg-text-field/trim-input/component.js

While investigating a bug in the Mobile I noticed that the Meter field in the CIS workflow wasn't searchable as it was before upgrading the API. It turns out we were only searching strings.
This PR allows numeric fields to be searchable by always stringifying the value of the field being passed in via searchProperty.

fix(dropdown): Allow searching of object fields that contain numeric values

---

addon/sidebar-menu-manager/service.js
package.json

Current user content was null when unauthenticated and caused an error when trying to call `hasRole()`.

fix: sidebar role error when unauthenticated

---

addon/styles/addon.scss

The modified Sass isn't the prettiest and I'm sure it could be written in a cleaner way, so I am open to feedback.

style(dropdown): Force dropdowns to have same font size as input

---

addon/components/nrg-dropdown/component.js
addon/components/nrg-dropdown/template.hbs
package.json
tests/integration/components/nrg-dropdown/component-test.js

This PR allows the dropdown to conform to keyboard typists using `Tab` and `Escape`. 
There are changes to better match Fomantic/Semantic JS version of the dropdown like adding the search placeholder.

 refactor(dropdown): improve keyboard navigation

---

addon/styles/_flash-messages.scss
package.json

Changed padding to margin which enables a click to pass through the toast-container to the context menu and version number.
Overrode the ui.toast-container to utilize a more purposeful z-index (9999 default) to allow the context menu to overlap flash messages in the event they are present and the user wants to view the context menu. #303

fix: Make context menu accessible when flash messages are present

---

addon/helpers/nrg-app-version.js
index.js
package.json

We expect the app version to display as the tag unless the current commit does not match what is on the tag. `ember-cli-app-version` would return just the version when there were no commits on top of the tag until [these changes](https://github.com/ember-cli/ember-cli-app-version/pull/68/files) were put into place. Now it always returns the version and commit SHA. Here I am using the same library they are to get the git info and adding the `commitsSinceLastTag` to the `APP` config. Then in the helper, if that number is 0, I try to display the extended version. If the regex match fails for that, it will try to get the unextended version. If the `commitsSinceLastTag` is not 0, then it will display the short commit SHA. To test these changes, I used yarn link to sym link this to …

fix: app version

---

addon/components/nrg-toast.hbs
addon/components/nrg-toast.js
package.json
tests/dummy/app/controllers/toasts.js
yarn.lock

The toast progress bar was not loading as expected and clicking on them did not dismiss them. I also removed the `mouseenter` and `mouseleave` modifiers, because those are not actions and everything seems to work fine without them (progress stops on `mouseenter `and resumes on `mouseleave`). I bumped the version in the last PR and have not released it yet, so I won't need to bump it here.

fix: nrg-toast progress and dismissal

---

addon/components/nrg-validation-component.js
addon/decorators/validation.js
tests/acceptance/form-validation-test.js
tests/dummy/app/controllers/validation-tests.js
tests/dummy/app/templates/validation-tests.hbs

The following changes were made:
* The `valuePath` property for all components extending `NrgValidationComponent` now supports nested values. This allows a property referencing a property on an object in the model to be used
* Validators support nested properties, where the key should be period-separated, eg. `nested.field`
* A single validator for a key in the validators object does not have to be wrapped in an array, it can be passed directly

feat(validations): Support nested value paths

---

addon/components/nrg-lightbox-container.js
addon/components/nrg-lightbox-thumbnail.js
addon/services/lightbox.js
package.json

By moving the `bottomDetails` property to the `lightbox` service, it can now be set when invoking the `NrgLightboxThumbnail` with `@bottomDetails` argument, and changes to the details location selected can be handled with the `@onBottomDetailsChange` argument.

feat(lightbox): Move bottomDetails to service and add ability to fire action on change

---

addon/styles/_side-by-side.scss
package.json

Recently (likely with the bump of Fomantic UI), lists used in the primary section of a side-by-side have an extra border visible:
Increasing the specificity of an existing rule fixes this issue:

chore(side-by-side): Bump CSS specificity to fix border with lists

---

addon/components/nrg-search.hbs
addon/components/nrg-search.js
package.json
tests/integration/components/nrg-search-test.js

Previously, the search component would only compute what value to display on initial rendering - meaning if the underlying model/valuePath changed, the displayed text would not be updated.

feat(search): Display input value dynamically

---

addon/components/nrg-datetime/calendar/component.js
package.json

This change fixes the error with the Datetime Calendar that was causing the calendar to be greyed out upon first click.

fix: Pass new Date if value is empty

---

addon/components/nrg-list.hbs
addon/components/nrg-list.js
addon/components/nrg-list/items.js
package.json
tests/dummy/app/components/freestyle/list.hbs
tests/dummy/app/components/freestyle/list.js

* Internally, the `nrg-list` component referenced actions that have since been deprecated on the `nrg-list/items` component. This has been resolved.
* Changing the `selectionType` of a list from `single` to `multiple` would break in determining if the newly selected item was included in the array of selected items.

fix(nrg-list): Prevent forced deprecation warning

---

addon/components/nrg-modal.hbs
package.json

The `did-insert` modifier that the `nrg-new-features` component passes to the `nrg-modal` component is never attached to a DOM element, since no passed-in attributes to `nrg-modal` components are used anywhere. This worked in previous Ember versions since all Ember components are wrapped in a `div` by default, which is also where attributes were placed. Therefore, the modifier was placed on the `div` wrapping the modal component; this `div` no longer exists.

fix(whats-new): Allow "What's New" modal to appear

---

addon/components/nrg-search.hbs
addon/components/nrg-search.js
addon/styles/_search.scss
addon/styles/addon.scss
package.json
tests/dummy/app/components/freestyle/search.hbs
tests/integration/components/nrg-search-test.js

Request to ease clearing the search in fieldwork on G2 devices since they hide the keyboard.

feat: New clear option on search

---

addon/components/nrg-side-by-side.hbs
addon/components/nrg-sidebar-menu/group.hbs
addon/components/nrg-sidebar-menu/item.hbs

This will allow us to test the sidebar items easier in kub-apps-core for the new role secure project. If this isn't the right way to do it please let me know.

feat: Adding data-test tags to sidebar item, group and side-by-side
